return { -- this table overrides highlights in all themes
      Normal = { bg = "NONE", ctermbg = "NONE" },
      NormalNC = { bg = "NONE", ctermbg = "NONE" },
      CursorColumn = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLine = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      LineNr = {},
      SignColumn = {},
      StatusLine = {},
      NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
      NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
      NeoTreeFloatTitle = { bg = "NONE", ctermbg = "NONE" },
      NeoTreeFloatBorder = { bg = "NONE", ctermbg = "NONE" },
      NotifyBackground = { bg = "#000000" },
      IblScope = { bg = "#000000" },
      IblIndent = {},
      IblWhitespace = {},
      WinBar = {},
      WinBarNC = { bg = "NONE" },
      TabLine = {},
      NormalFloat = { bg = "NONE" },
}
